language: scala

scala:
  - 2.11.12
  - 2.12.8

sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - sbt "++ ${TRAVIS_SCALA_VERSION}! -v" test
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
