language: scala

dist: xenial

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0

sudo: false

jdk:
  - openjdk8

matrix:
  include:
  - scala: 2.12.8
    jdk: openjdk11

cache:
  directories:
    - $HOME/.ivy2/cache

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - sbt "++ ${TRAVIS_SCALA_VERSION}! -v" test
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
